web:
  image: nginx:latest
  ports:
    - "80:80"
  volumes:
    - /home/anjun/svn/address_order:/code
    - ./site.conf:/etc/nginx/conf.d/site.conf
  links:
    - php
php:
  # image: php:5.6-fpm
  build: ./fpm
  volumes:
    - /home/anjun/svn/address_order:/code